apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: jenkins-master
    name: jenkins-master
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jenkins-master
    template:
      metadata:
        labels:
          app: jenkins-master
      spec:
        containers:
        - image: gcr.io/liquid-sylph-273719/jenkins-master:v1
          name: jenkins-master
          env:
            - name: JAVA_ARGS
              value: -Djenkins.install.runSetupWizard=false
          volumeMounts:
            - name: jenkins-init-config
              mountPath: /var/jenkins_home/init.groovy.d
        terminationGracePeriodSeconds: 30
        volumes:
          - name: jenkins-init-config
            configMap:
              name: jenkins-init
kind: List
